### ISSUE TITLE
Variouse UI issues

### ISSUE THREAD

**Issue by cj2tech** [SlippingGittys-Discord-Themes/Diskette#11]
:: Diskette Version::
6.24

:: System Info::
Windows 11 64-bit (10.0.22631)

:: Discord Version ::
Build Number: 309513

:: Theme Mod ::
OpenAsar Nightly (5c875eb)

:: Current CSS in uses :: 
https://pastebin.com/HkLLBU38

:: Issue(s) ::
1. Unable to scroll Server Browsers. was mention in https://github.com/SlippingGittys-Discord-Themes/Diskette/issues/10
2. In friends upper container (think its `div class="upperContainer_fc4f04'`) has no theme applied
![image](https://github.com/user-attachments/assets/5e9ff32e-54c1-49dc-a98f-060de4b28468)
3. Windows Close, minimize, and maximize buttons are misplaced
![image](https://github.com/user-attachments/assets/76f1c63f-fef7-4066-bebf-ad3f12160692)
4. Unable to close any Reconnect/Streamer mode prompt due to misalignment.
![image](https://github.com/user-attachments/assets/ec153c25-80be-4500-ba77-27abb181651b)

Hope all this helps. Love this theme.  Been looking for a better them that is apart of that vapor-wave/cyberpunk theme and none could even hold a candle to this one. Would love to see the above fixed. Thanks for all the cool work and stuff. Also love the little Easter eggs that you put in the repo. ᵗᵃˢᵏ ᵐᵃⁿᵃᵍᵉʳ ⁱˢ ᵐᵃᵍⁱᶜᵃˡ ᵛᵘᵈᵒ.

Much love <3

**Comment by TacticalDeux** [comment]
(all changes to selector.css) the guild scrolling issue, for now, can be fixed by removing this entirely (or removing/changing only `position`, and fixing padding and positioning):
```css
/* Guilds Placement */
.scroller_fea3ef {
  position: fixed !important;
  top: 20px !important; 
  padding-left: 10px !important; 
}
```
Title bar fix:
```css
.theme-dark .themed_fc4f04 { /* was .themed_e44302 */
   background-color: var(--projectCabTitleBar);
   border: var(--borders);
   margin: 0 0 10px 10px;
   width: calc(100% - 25px);
   padding: 0px;
}

.theme-dark .themed_fc4f04:hover { /* was .themed_e44302 */
   border-color: var(--bordersH);
}
```
and this:
```css
/* Friends Icon (Title Bar) */
.children_fc4f04>.iconWrapper_fc4f04{ /* was .children_e44302>.iconWrapper_e44302 */
   display: none;
}
```
And the title bar has now a kinda fade effect which gets left over and looks weird when making the bg transparent, so that can be removed by this:
```css
/* Friends Title bar fade effect (why is this a thing) */
.children_fc4f04:after {
  display: none;
}
```
You can either wait for Vozy to fix these or, download [`selector.css`](https://slippinggittys-discord-themes.github.io/Diskette/User/Vozy/Documents/source%20files/everything%20else/selectors.css) making the changes/swaps, and change `Diskette.theme.css` to point to it
```css
/*  🔌🔌🔌 Diskette Plugin - Do NOT Eject 🔌🔌🔌 */
@import url('path/to/file/here');
```
Or the far simpler and quicker way which is to add the fixes to your QuickCSS, and probably add `!important` at the end of all the attributes just to make sure there's no specificity issues, like this:
```css
/* Friends Icon (Title Bar) */
.children_fc4f04>.iconWrapper_fc4f04{ /* was .children_e44302>.iconWrapper_e44302 */
   display: none !important;
}
```
Just remember to remove them once the theme gets fixed or it might fuck with future changes because of the `!important` flag.
