### ISSUE TITLE
Where do you define font color

### ISSUE THREAD

**Issue by drakosoldier298** [SlippingGittys-Discord-Themes/Diskette#14]
i have looked through the code manually and cant..seem to find it

**Comment by ghost** [comment]
hi @drakosoldier298, if you're asking how to change the font color properly: you may change the following discord variables
```css
/* replace "red" with your desired color */
.theme-dark {
    --text-normal: red;
    --text-muted: red;
    --interactive-active: red;
    --interactive-hover: red;
    --interactive-muted: red;
    --interactive-normal: red;
    --header-primary: red;
    --header-secondary: red;
    --channels-default: red;
    --channel-icon: red;
    --input-placeholder-text: red;
    --channel-text-area-placeholder: red;
}
```
there are probably more, you can look for them yourself using devtools (<kbd>ctrl</kbd> + <kbd>shift</kbd> + <kbd>i</kbd>) inside the app.

else if you're asking about the base theme - it doesn't change the text colors. other color schemes available for diskette are currently doing this in hacky/wrong ways since they haven't been rewritten yet (fixing this is on my to-do but not a priority).
